#XcraftBreedLimit config
Breeding:
    Radius: 2
    Limits:
        SHEEP: 100
        COW: 30
        CHICKEN: 30
        PIG: 30
        OCELOT: 0
        WOLF: 0
        HORSE: 0
    Message:
        default: '&cDas Tier zittert vor Nervositaet. Es fuehlt sich zu bedraengt zum Zuechten!'
        
