name: XcraftBreedLimit
main: de.xcraft.INemesisI.BreedLimit.XcraftBreedLimit
version: 1.1
author: INemesisI

commands:
  bl:
    usage: /bl reload
  licence: 
    usage: /licence buy/list/give
    
permissions:
    breedlimit.reload:
        description: Access reload command
        default: op
    breedlimit.exempt:
        description: Access to ignore the breedlimit
        default: op
