name: XcraftBreedLimit
version: 1.2.3
author: INemesisI

main: de.xcraft.INemesisI.BreedLimit.XcraftBreedLimit
load: POSTWORLD
softdepend: [Vault]

commands:
  breedlimit:
    aliases: bl
  licence: 
    aliases: l
    
permissions:
    XcraftBreedLimit.Scan:
        default: op
    XcraftBreeLimit.Licence:
        default: op
    XcraftBreedLimit.Exempt:
        default: op
