name: XcraftBreedLimit
version: 1.3.3
author: INemesisI
description: Requires XcraftLibrary v1.6.0

main: de.xcraft.INemesisI.BreedLimit.XcraftBreedLimit
load: POSTWORLD

depend: [XcraftLibrary]
softdepend: [Vault]

commands:
  breedlimit:
    aliases: bl
    
permissions:
    XcraftBreedLimit.Scan:
        default: op
    XcraftBreedLimit.Exempt:
        default: op
